cacheFolder: ./.yarn/cache

compressionLevel: mixed

enableGlobalCache: false

# httpProxy: "http://127.0.0.1:7890"

nodeLinker: node-modules

npmPublishRegistry: "https://registry.npmjs.org"

progressBarStyle: patrick

yarnPath: .yarn/releases/yarn-4.6.0.cjs
