# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["tauri/src-tauri"]
resolver = "2"

[workspace.package]
version = "0.0.1"
authors = ["Han <han@deskbtm.com>"]
repository = "https://github.com/deskbtm-publish/publish"
rust-version = "1.70"
edition = "2021"

[workspace.dependencies]
serde_json = "1.0"
serde = "1.0"
tauri = "2.0.0-beta.11"
tauri-build = "2.0.0-beta.9"
tauri-plugin-shell = "2.0.0-beta.2"
wry = "0.37"
windows = "0.52"
webview2-com = "0.28"
